A3: Number Conversion game
Jeevitha-Radei/Assignment pull request #2
Opened 2024-08-28 06:12 UTC by Jeevitha-Radei

2024-08-28 06:25 UTC, dineshN52 commented on PracticeGit/conversion.c
> +   if (n == 0) {   // Handle zero case
Try switch cases, in case of multiple if statements

2024-08-28 06:26 UTC, dineshN52 commented on PracticeGit/conversion.c
> +   if (n == 0) {
Try switch cases

2024-08-28 06:42 UTC, dineshN52 commented on PracticeGit/conversion.c
> +   for (int j = i - 1; j >= 0; j--) printf ("%d", binaryNum[j]);     // Print binary number in reverse order
Create a single method for printing values

2024-08-28 06:46 UTC, dineshN52 commented on PracticeGit/conversion.c
> +      n = n / 2;
Use compound statements, n/=2.

2024-08-28 06:47 UTC, dineshN52 commented on PracticeGit/conversion.c
> +      n = n / 16;
Use compound statement

2024-08-28 07:03 UTC, dineshN52 commented on PracticeGit/conversion.c
> +      printf ("Input: %d\n", decimalNumber);
Common conditions like Zero check and negative check can be done in main itself

2024-08-28 07:04 UTC, dineshN52 requested changes
reviews

2024-08-29 07:04 UTC, dineshN52 requested changes

2024-08-29 07:04 UTC, dineshN52 commented on PracticeGit/conversion.c
> +   unsigned int num = (unsigned int)n; // To handle negative numbers in two's complement
Instead use bitwise shift method to get binary values

2024-08-29 07:04 UTC, dineshN52 commented on PracticeGit/conversion.c
> +   if (result == 2 && ((term == '\n') || (term == ' '))) {
Modify the loop until valid integer is inputted, as it breaks after an invalid integer

2024-09-03 09:23 UTC, dineshN52 commented on PracticeGit/conversion.c
>           printf ("\n");
No need to print two new lines

2024-09-03 09:23 UTC, dineshN52 commented on PracticeGit/conversion.c
> +      for (int i = 0; i < BITS; i++) binary[i] = (temp >> i) & 1;  // Convert to binary
Try to implement binary conversion as separate method irrespective of number of bits and try using it here

2024-09-03 09:23 UTC, dineshN52 commented on PracticeGit/conversion.c
> +      for (int i = 0; i < BITS; i++) binary[i] = 1 - binary[i];  // Invert the bits
Create a new method for finding two's compliment for a binary number

2024-09-03 09:23 UTC, dineshN52 commented on PracticeGit/conversion.c
> +         if (digit < 10) hexDigits[hexIndex++] = digit + '0';
Repetition of same method, incorporate as single method

2024-09-05 04:52 UTC, ShakthyTMM requested changes
Write code to test your implementation.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +         DecToBinary (decimalNumber, binary, BITS);
I would suggest having this binary[BITS] as a global array instead of passing as an argument to the functions.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +      printf ("Input: ");
Add more descriptive prompts to guide the user. For example, "Please enter an integer: " instead of just "Input: ".

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +   for (int i = 0; i < 8; i++) printf ("%c", hexDigits[i]);
Return the result and print it in the main or have a separate function as done for binary. The function should contain only the functionality.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +}
Leave a line here.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +#pragma warning(disable:4996)
Move this line below the multi-line comment.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +         printf ("\n");
Move these lines printf("Binary:); printf("\n); to PrintBinary() function so as to have a clean code in main.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +         PrintBinary (binary, BITS);
As BITS is defined globally, don't need to pass to the functions. Apply this wherever necessary.

2024-09-05 04:52 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +         printf ("HEX: ");
Improve the message as "Hexadecimal Equivalent for (decimal number given):". Likewise print for binary also.

2024-09-06 06:08 UTC, ShakthyTMM requested changes

2024-09-06 06:08 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +         if (inputNumber < INT_MIN || inputNumber > INT_MAX)  printf ("Value out of range for a 32-bit signed integer. Try again.\n"); // Check if the input is within the valid range for a 32-bit sig
Many lines are similar in both RunTestCases() AND RunInput(). Put them into a function and use wherever necessary or I would also suggest having a single function and prompting the user whether he/she wants to run the test cases or enter input.

2024-09-06 06:08 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +
Remove this line.

2024-09-06 06:08 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +}
Please leave a line after every function.

2024-09-06 06:08 UTC, ShakthyTMM commented on PracticeGit/conversion.c
> +         DecToBinary (decimalNumber);
The output and the test cases have to be checked if they are equal. here you are just printing the output and test cases. Please check it.

2024-09-09 10:21 UTC, ShakthyTMM requested changes

2024-09-09 10:21 UTC, ShakthyTMM commented on PracticeGit/test.c
> +
Please remove this line.

2024-09-09 10:21 UTC, ShakthyTMM commented on PracticeGit/test.c
> +               DecToBinary (decimalNumber);
These five lines are repeating in the if else block. Move it to a separate helper method and use it.

2024-09-09 10:21 UTC, ShakthyTMM commented on PracticeGit/test.c
> +      printf (YELLOW "Select option : "RESET" \n");
The interface is very good.

2024-09-09 10:21 UTC, ShakthyTMM commented on PracticeGit/test.c
> +          {100, "00000000 00000000 00000000 01100100", "00000064"},
Please test for failing cases also.

2024-09-10 10:53 UTC, Dakshita-Minocha approved these changes

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/conversion.c
> +int binary[BITS];   // Global array to hold binary representation
You should avoid using Global Variables (as pointed out in yesterday's session

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/conversion.c
> +   return (value < 10) ? (char)(value + '0') : (char)(value - 10 + 'A');
This function call is not required. While the statement is repeated, if is only one statement. You can just assign the value.

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/test.c
> +      }
![image](https://github.com/user-attachments/assets/9554dc48-dbb6-4ce9-bd71-ffd8e6e8f024)
This is actually a passing case. The expected value is an error and that is what you're getting.

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/conversion.c
> +void FormatBinary (char formattedBinary[BITS / 8 * 9 + 1]) {
```suggestion
void FormatBinary (char formattedBinary[]) {
```
See [here](https://stackoverflow.com/questions/15542697/c-function-argument-char-vs-char#:~:text=All%20strings%20are%20pointers%20to%20arrays%20of%20char%2C,just%20another%20way%20of%20writing%20the%20same%20thing.)

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/test.c
> +         long long input;
Avoid using long long wherever possible

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/conversion.c
> +void DecimalToHexadecimal (char hexString[HEX_LENGTH + 1]) {
You should only take in integer values in your library function

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/test.c
> +      if (scanf ("%d", &choice) != 1) {
See [here](https://c-faq.com/stdio/scanfprobs.html)

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/test.c
> +   if (isTest) {
```suggestion
   if (!isTest) return;
```
https://en.wikipedia.org/wiki/Guard_(computer_science)

2024-09-10 10:53 UTC, Dakshita-Minocha commented on PracticeGit/test.c
> +         const char* expectedBinary;
*Input, ExpectedBinary, ExpectedHexadecimal

2024-09-10 10:54 UTC, closed without merging