FSM implementation in C
Jeevitha-Radei/Assignment pull request #5
Opened 2024-11-18 04:40 UTC by Jeevitha-Radei

2024-11-29 09:32 UTC, ShakthyTMM requested changes

2024-11-29 09:32 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +      }
```suggestion
*output = 0;
return input ? S6 : S1;
```

2024-11-29 09:32 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +State mealyState (State currentState, int input, int* output) {
Please follow the naming conventions. By this time, you should be able to do it correctly.

2024-11-29 09:32 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +   }
These two if blocks can be put up in a single if block.

2024-11-29 09:32 UTC, ShakthyTMM commented on PracticeGit/FSMTest.c
> +int compareFiles (const char* file1, const char* file2) {
Please simplify this function.

2024-12-11 08:46 UTC, Ashish02112001 commented on PracticeGit/FSM6A.c
> +   case S2:
Check the spacing and correct wherever necessary

2024-12-11 08:46 UTC, Ashish02112001 commented on PracticeGit/FSM6A.c
> +      *output = 0;
Cases must be indented a tab space inside switch statement

2024-12-23 10:14 UTC, ShakthyTMM requested changes
Have a separate folder _**TData**_ to store all the input and reference files. This folder should not be a part of the solution (should not be pushed).

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +         *output = 0;
Take *output outside the switch case.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +         }
Apply ternary operator wherever possible.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +typedef enum {
Have a state for invalid value.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +/// State diagram reference: file://C:/Work/Training24/PracticeGit/Assignment6A.jpg
I will not be able to view the file as its absolute path is given. You can remove this line, as the file is added to the solution.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +         fprintf (outputFile, "%d", output);
Avoid writing output file for every bit. Hold your output, after completing write only once to the file.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSMTest.c
> +      snprintf (expectedOutputFile, sizeof (expectedOutputFile), "test%dout.txt", i + 1);
Use and reuse only a single output file.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSM6A.c
> +      return 1;
Have error codes and return them.

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSMTest.c
> +      if (ExecProgram (argv[1], (char*)inputFile, generatedOutputFile) != 0) printf ("\nError executing test %d\n", i + 1);
```suggestion
      if (ExecProgram (argv[1], (char*)inputFile, generatedOutputFile)) printf ("\nError executing test %d\n", i + 1);
```

2024-12-23 10:14 UTC, ShakthyTMM commented on PracticeGit/FSMTest.c
> +      char expectedOutputFile[256];         // Construct the expected reference output file name
Why 256?

2024-12-31 10:16 UTC, Dakshita-Minocha commented on PracticeGit/FSM6A.c
> +         *output = (input == 0) ? 1 : 0;  // output '1' upon seeing '0110', else '0'
output = !input

2024-12-31 10:16 UTC, Dakshita-Minocha commented on PracticeGit/FSM6A.c
> +         *output = (input == 1) ? 1 : 0;  // output '1' upon seeing '1101', else '0'
output = input

2024-12-31 10:16 UTC, Dakshita-Minocha commented on PracticeGit/FSM6A.c
> +   *output = 0;
keep output assignment within the case. the slight fluctuation in output value from output = 1 to 0 to 1 has the potential to cause errors in specific situations.

2024-12-31 10:16 UTC, Dakshita-Minocha commented on PracticeGit/FSM6A.c
> +         return INVALID; // Stay in INVALID state for invalid inputs
This is covered by default

2024-12-31 10:16 UTC, Dakshita-Minocha commented on PracticeGit/FSM6A.c
> +            fclose (outputFile);
This code is repeated, and as such can be separated out to a function

2024-12-31 12:03 UTC, Dakshita-Minocha commented on PracticeGit/FSMTest.c
> +int compareFiles (const char* file1, const char* file2);
Follow naming conventions

2024-12-31 12:03 UTC, Dakshita-Minocha commented on PracticeGit/FSMTest.c
> +// FSMtest.c
Don't rename files given to you as reference -> Always make only necessary changes.

2024-12-31 12:03 UTC, Dakshita-Minocha commented on PracticeGit/FSMTest.c
> +   int bitNum = 1;
Better to compare file lengths first, it is a more efficient way to compare than brute force comparison.

2024-12-31 12:03 UTC, Dakshita-Minocha commented on PracticeGit/FSMTest.c
> +      if (ch1 != ch2) {   // Compare the characters
The only valid condition here is ch1!=ch2. None of the other conditions should be taken into account. Also, ch1 and ch2 have not been named appropriately.

2024-12-31 12:03 UTC, Dakshita-Minocha commented on PracticeGit/FSMTest.c
> +      }
```suggestion
      else  if (!compareFiles (outputFile, expectedOutputFile)) {
            printf ("\nTest %d failed at output for %s\n", i + 1, inputFile);
            return 1;  // Exit immediately on failure
         }
      }
```

2025-01-01 09:59 UTC, Dakshita-Minocha approved these changes

2025-01-01 09:59 UTC, closed without merging