Test2: Cash Return
Jeevitha-Radei/Assignment pull request #9
Opened 2024-11-28 17:31 UTC by Jeevitha-Radei

2024-11-29 09:33 UTC, ShakthyTMM commented
Branch name is incorrect. Follow the instructions given.

2024-12-04 11:40 UTC, Dakshita-Minocha requested changes

2024-12-04 11:40 UTC, Dakshita-Minocha commented on PracticeGit/Cash.h
> +/// <summary>Generate the changes for the given amount.</summary>
When providing a desc for a function, you must document what it returns (especially if you have a special value like -1 being returned)

2024-12-04 11:40 UTC, Dakshita-Minocha commented on PracticeGit/PracticeGit.vcxproj
> +    <ClCompile Include="Cash.c" />
Since this is an interactive program with a user (not a library), a header file is not really required.

2024-12-04 11:40 UTC, Dakshita-Minocha commented on PracticeGit/TestCash.c
> +               pass = 0;
I don't understand why you are printing pass and fail in a user program? Tests are meant for developers and developers only. If you have any doubts regarding tests please ask.

2024-12-26 06:21 UTC, Dakshita-Minocha commented on PracticeGit/Cash.c
> +      printf ("Negative value encountered. Cash Paid and Actual Amount must be non-negative.\n");
You should not print in library functions.

2024-12-26 08:16 UTC, Dakshita-Minocha reviewed
These changes are not at all the ones suggested to you. Please READ the reviews before you make changes. Come and see me.

2024-12-31 10:17 UTC, Dakshita-Minocha approved these changes

2024-12-31 10:17 UTC, closed without merging